spring:
  # flyway:
  #   baseline-on-migrate: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rest_with_spring_calculadora?useTimezone=true&serverTimezone=UTC
    username: root
    password: senhasecreta
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    # format_sql: false
    # show_sql: false